baseurl = ""
metaDataFormat = "yaml"
title = "My Ramblings "
theme = "blist"



DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true


[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true
  enableHeaderMenu = false

  introTitle = "Salutations👋 I'm Robert"
  introSubtitle = "Big Data Engineer, Cloud lover, Linux Advocate and will dockerise anything I touch"
  introPhoto = "/picture.jpg"
  
  contentDir = "content" #English

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Robert Fletcher · All rights reserved"
  favicon = "/favicon.ico"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-green-300"


[[menu.main]]
    name = "Blog"
    url = "blog"
    weight = 1


[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "I work on everything coding"
  twitter = "https://twitter.com/robrotheram"
  linkedin = "https://linkedin.com/in/robrotheram"
  github = "https://github.com/robrotheram"
  instagram = "https://gallery.exceptionerror.io/"
  

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
