apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog.exceptionerror.io.fullname" . }}
  labels:
    {{- include "blog.exceptionerror.io.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: blog-http
      protocol: TCP
      name: blog-http
  selector:
    {{- include "blog.exceptionerror.io.selectorLabels" . | nindent 4 }}
