replicaCount: 1
image:
  repository: ghcr.io/robrotheram/blog
  pullPolicy: IfNotPresent
  tag: latest
  commit: 6fa390e57b17274686e28208ec339e1c58e70c8b
imagePullSecrets: []
nameOverride: ''
fullnameOverride: blog-exceptionerror-io
podAnnotations: {}
service:
  port: 3000
ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: blog.exceptionerror.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
