replicaCount: 1
image:
  repository: ghcr.io/robrotheram/blog
  pullPolicy: Always
  tag: latest
  commit: 3f7cf018d8b2019b9e8cbd35aaf6d106df4de61c
imagePullSecrets: []
nameOverride: ''
fullnameOverride: blog-exceptionerror-io
podAnnotations: {}
service:
  port: 3000
ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt-staging
  hosts:
    - host: blog.exceptionerror.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - blog.exceptionerror.io
      secretName: staging-blog-tls
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
