replicaCount: 1
image:
  repository: ghcr.io/robrotheram/blog
  pullPolicy: Always
  tag: latest
  commit: c26aa34bdd2c298698e5fa4784f80b0006a87759
imagePullSecrets: []
nameOverride: ''
fullnameOverride: blog-exceptionerror-io
podAnnotations: {}
service:
  port: 3000
ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt-production
  hosts:
    - host: blog.exceptionerror.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - blog.exceptionerror.io
      secretName: production-blog-tls
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
