# Default values for blog.exceptionerror.io.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/robrotheram/blog
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  commit: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "blog-exceptionerror-io"

podAnnotations: {}

service:
  port: 3000

ingress:
  enabled: true
  className: ""
  annotations: 
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: blog.exceptionerror.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
