replicaCount: 1
image:
  repository: ghcr.io/robrotheram/blog
  pullPolicy: Always
  tag: latest
  commit: 505f4a03570d14ff671cb4751de32622bca280b3
imagePullSecrets: []
nameOverride: ''
fullnameOverride: blog-exceptionerror-io
podAnnotations: {}
service:
  port: 3000
ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: "letsencrypt-staging"
  hosts:
    - host: blog.exceptionerror.io
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
    - blog.exceptionerror.io
    secretName: staging-blog-tls 
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
